// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Speedrun.Data;

#nullable disable

namespace Speedrun.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250111094615_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Speedrun.Models.Oras", b =>
                {
                    b.Property<int>("CodOras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodOras"));

                    b.Property<int>("CodTara")
                        .HasColumnType("int");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("NumarulLocuitori")
                        .HasColumnType("int");

                    b.HasKey("CodOras");

                    b.HasIndex("CodTara");

                    b.ToTable("Oras", (string)null);
                });

            modelBuilder.Entity("Speedrun.Models.Tara", b =>
                {
                    b.Property<int>("CodTara")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodTara"));

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CodTara");

                    b.ToTable("Tara", (string)null);
                });

            modelBuilder.Entity("Speedrun.Models.Oras", b =>
                {
                    b.HasOne("Speedrun.Models.Tara", "Tara")
                        .WithMany("Orase")
                        .HasForeignKey("CodTara")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tara");
                });

            modelBuilder.Entity("Speedrun.Models.Tara", b =>
                {
                    b.Navigation("Orase");
                });
#pragma warning restore 612, 618
        }
    }
}
